### ISSUE TITLE
Stratified Shuffle Split 

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#112]
Sklearn's stratified shuffle split fails if it cannot find stratified split.

Should catch exception, then either use regular shuffle split or not split at all.

```
Namespace(configuration_file='/dsbox_efs/config/seed-41/partition-32/313_spectrometer/search_config.json', cpus=10, debug=False, output_prefix=None, timeout=55)
Using configuation:
{'cpus': 10,
 'dataset_schema': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_dataset/datasetDoc.json',
 'executables_root': '/dsbox_efs/runs/seed/313_spectrometer/executables',
 'pipeline_logs_root': '/dsbox_efs/runs/seed/313_spectrometer/pipelines',
 'problem_root': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_problem',
 'problem_schema': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_problem/problemDoc.json',
 'temp_storage_root': '/dsbox_efs/runs/seed/313_spectrometer/supporting_files',
 'timeout': 55,
 'training_data_root': '/dsbox_efs/dataset/seed_datasets_current/313_spectrometer/313_spectrometer_dataset',
 'user_problems_root': '/dsbox_efs/runs/seed/313_spectrometer/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] - dsbox.controller.controller - Top level output directory: /dsbox_efs/runs/seed/313_spectrometer
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' Default_classification_template ' has been added to template base.
Template ' random_forest_template ' has been added to template base.
Template ' DSBox_classification_template ' has been added to template base.
Template ' TA1Classification_3 ' has been added to template base.
Template ' MuxinTA1ClassificationTemplate1 ' has been added to template base.
Template ' TA1_classification_template_1 ' has been added to template base.
Traceback (most recent call last):
  File "ta2-search", line 173, in <module>
    result = main(args)
  File "ta2-search", line 102, in main
    status = controller.train()
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 585, in train
    problem_info = self.problem_info, problem_loc = self.config['problem_schema'])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 169, in split_dataset
    for train_index, test_index in sss.split(dataset[res_id], dataset[res_id].iloc[:, target_index]):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 1204, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 1546, in _iter_indices
    raise ValueError("The least populated class in y has only 1"
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```

**Comment by kyao** [comment]
Fixed by https://github.com/usc-isi-i2/dsbox-ta2/commit/3f79bb0ac5894005dbd31ee6e95b787d8b976b93
