### ISSUE TITLE
Cleaning featurizer bug

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#114]
```
Namespace(configuration_file='/dsbox_efs/config/seed-41/partition-36/26_radon_seed/search_config.json', cpus=10, debug=False, output_prefix=None, timeout=55)
Using configuation:
{'cpus': 10,
 'dataset_schema': '/dsbox_efs/dataset/seed_datasets_current/26_radon_seed/26_radon_seed_dataset/datasetDoc.json',
 'executables_root': '/dsbox_efs/runs/seed/26_radon_seed/executables',
 'pipeline_logs_root': '/dsbox_efs/runs/seed/26_radon_seed/pipelines',
 'problem_root': '/dsbox_efs/dataset/seed_datasets_current/26_radon_seed/26_radon_seed_problem',
 'problem_schema': '/dsbox_efs/dataset/seed_datasets_current/26_radon_seed/26_radon_seed_problem/problemDoc.json',
 'temp_storage_root': '/dsbox_efs/runs/seed/26_radon_seed/supporting_files',
 'timeout': 55,
 'training_data_root': '/dsbox_efs/dataset/seed_datasets_current/26_radon_seed/26_radon_seed_dataset',
 'user_problems_root': '/dsbox_efs/runs/seed/26_radon_seed/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] - dsbox.controller.controller - Top level output directory: /dsbox_efs/runs/seed/26_radon_seed
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' Default_regression_template ' has been added to template base.
Template ' DSBox_regression_template ' has been added to template base.
Template ' UU3_Test_Template ' has been added to template base.
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 0:SRI_Mean_Baseline_Template Selected. UCT:[None, None, None, None]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it wi\
ll be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 2942322042046054928)
[INFO] Testing finish.!!!
[INFO] Now in normal mode, will add extra train with train_dataset1
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 2942322042046054928)
[INFO] Now are training the pipeline with all dataset and saving the pipeline.
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', 2942322042046054928)
[INFO] push@Candidate: (5739992804555506563,8f6019de-9ffb-47b6-bf39-7f18d343d900)
[INFO] - dsbox.controller.controller - ******************
[INFO] Writing results
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7fa56e479828>,
 'test_metrics': [{'metric': 'rootMeanSquaredError',
                   'value': 0.783760618048308}],
 'total_runtime': 216.7820348739624,
 'training_metrics': [{'metric': 'rootMeanSquaredError',
                       'value': 0.8428079925434945}]}
[INFO] - dsbox.controller.controller - {'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7fa56e479828>, 'training_metrics': [{'metric': 'rootMeanSquaredErr\
or', 'value': 0.8428079925434945}], 'cross_validation_metrics': [], 'test_metrics': [{'metric': 'rootMeanSquaredError', 'value': 0.783760618048308}], 'total_runtime': 216.7820348739624\
} 0.783760618048308
[INFO] - dsbox.controller.controller - Training rootMeanSquaredError = 0.8428079925434945
[INFO] - dsbox.controller.controller - Validation rootMeanSquaredError = 0.783760618048308
[INFO] - dsbox.controller.controller - ******************
[INFO] Saving training results in /dsbox_efs/runs/seed/26_radon_seed.txt
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] report: 0.783760618048308
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] UCT updated: [12.488022799916767, 132.5776429061736, 132.5776429061736, 132.5776429061736]
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] cache size: 1, candidates: 1
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 1:Default_regression_template Selected. UCT:[12.488022799916767, 132.5776429061736, 132.5776429061736, 132.5776429061\
736]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use cross validation( n = 10 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.dsbox.Denormalize', 2942322042046054928)
[INFO] Push@cache: ('d3m.primitives.datasets.DatasetToDataFrame', 2942322042046054928)
[INFO] Push@cache: ('d3m.primitives.data.ExtractColumnsBySemanticTypes', 5018187021572064357)
[INFO] Push@cache: ('d3m.primitives.data.ExtractColumnsBySemanticTypes', 2919905420241308080)
[INFO] Push@cache: ('d3m.primitives.dsbox.Profiler', -6557345892620110405)
[INFO] Push@cache: ('d3m.primitives.dsbox.CleaningFeaturizer', -6557345892620110405)
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 523, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 546, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset1])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 94, in fit
    self.runtime.fit(**arguments)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 195, in fit
    primitive_arguments
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 284, in _primitive_step_fit
    produce_result = model.produce(**produce_params)
  File "/user_opt/dsbox/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/cleaning_featurizer.py", line 200, in produce
    df = PunctuationParser.perform(df=self._input_data_copy, columns_perform=self._mapping.get("punctuation_columns"))
  File "/user_opt/dsbox/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/dependencies/spliter.py", line 144, in perform
    new_df = update_type(extends, df)
  File "/user_opt/dsbox/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/dependencies/spliter.py", line 14, in update_type
    extends_df.index = df_origin.index.copy()
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 3627, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 559, in _set_axis
    self._data.set_axis(axis, labels)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals.py", line 3074, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 735 elements
```

**Comment by ckxz105** [comment]
fixed after this version https://github.com/usc-isi-i2/dsbox-cleaning/commit/c91e440caa8e79897f819a4d8198dc9ad9ed657b
