### ISSUE TITLE
cleaner/dependencies/dtype_detector.py Error

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#117]
See /dsbox_efs/runs/seed-2018-07-26-02:04/32_wikiqa/

```
Namespace(configuration_file='/dsbox_efs/config/seed-41/partition-14/32_wikiqa/search_config.json', cpus=10, debug=False, output_prefix=None, timeout=55)
Using configuation:
{'cpus': 10,
 'dataset_schema': '/dsbox_efs/dataset/seed_datasets_current/32_wikiqa/32_wikiqa_dataset/datasetDoc.json',
 'executables_root': '/dsbox_efs/runs/seed/32_wikiqa/executables',
 'pipeline_logs_root': '/dsbox_efs/runs/seed/32_wikiqa/pipelines',
 'problem_root': '/dsbox_efs/dataset/seed_datasets_current/32_wikiqa/32_wikiqa_problem',
 'problem_schema': '/dsbox_efs/dataset/seed_datasets_current/32_wikiqa/32_wikiqa_problem/problemDoc.json',
 'temp_storage_root': '/dsbox_efs/runs/seed/32_wikiqa/supporting_files',
 'timeout': 55,
 'training_data_root': '/dsbox_efs/dataset/seed_datasets_current/32_wikiqa/32_wikiqa_dataset',
 'user_problems_root': '/dsbox_efs/runs/seed/32_wikiqa/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] - dsbox.controller.controller - Top level output directory: /dsbox_efs/runs/seed/32_wikiqa
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' Default_classification_template ' has been added to template base.
Template ' random_forest_template ' has been added to template base.
Template ' DSBox_classification_template ' has been added to template base.
Template ' TA1Classification_3 ' has been added to template base.
Template ' MuxinTA1ClassificationTemplate1 ' has been added to template base.
Template ' TA1_classification_template_1 ' has been added to template base.
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 0:SRI_Mean_Baseline_Template Selected. UCT:[None, None, None, None, None, None, None]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float\
64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.sri.baseline.MeanBaseline', -7800897392389633829)
[INFO] Testing finish.!!!
[INFO] Now in normal mode, will add extra train with train_dataset1
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', -7800897392389633829)
[INFO] Now are training the pipeline with all dataset and saving the pipeline.
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', -7800897392389633829)
[INFO] push@Candidate: (-6298118050939978135,00ae6236-5084-41e2-b8f8-36038e2abaca)
[INFO] - dsbox.controller.controller - ******************
[INFO] Writing results
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7fdaae10af60>,
 'test_metrics': [{'metric': 'f1', 'value': 0.0}],
 'total_runtime': 211.6762125492096,
 'training_metrics': [{'metric': 'f1', 'value': 0.0}]}
[INFO] - dsbox.controller.controller - {'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7fdaae10af60>, 'training_metrics': [{'metric': 'f1', 'value': 0.0}], 'cross_validation_metri\
cs': [], 'test_metrics': [{'metric': 'f1', 'value': 0.0}], 'total_runtime': 211.6762125492096} 0.0
[INFO] - dsbox.controller.controller - Training f1 = 0.0
[INFO] - dsbox.controller.controller - Validation f1 = 0.0
[INFO] - dsbox.controller.controller - ******************
[INFO] Saving training results in /dsbox_efs/runs/seed/32_wikiqa.txt
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] report: 0.0
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] UCT updated: [12.47410727909658, 122.53848769797173, 122.53848769797173, 122.53848769797173, 122.53848769797173, 122.53848769797173, 122.53848769797173]
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] cache size: 1, candidates: 1
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 1:Default_classification_template Selected. UCT:[12.47410727909658, 122.53848769797173, 122.53848769797173, 122.53848769797173, 122.53848769797\
173, 122.53848769797173, 122.53848769797173]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use cross validation( n = 10 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.dsbox.Denormalize', -7800897392389633829)
[INFO] Push@cache: ('d3m.primitives.datasets.DatasetToDataFrame', -7800897392389633829)
[INFO] Push@cache: ('d3m.primitives.data.ExtractColumnsBySemanticTypes', 8763759074183313446)
[INFO] Push@cache: ('d3m.primitives.data.ExtractColumnsBySemanticTypes', -3142946526368382446)
[INFO] Push@cache: ('d3m.primitives.dsbox.Profiler', 2117814574191440618)
Traceback (most recent call last):
  File "/user_opt/dsbox/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/dependencies/dtype_detector.py", line 47, in detector
    if dtype.loc[True][0] == temp.dropna().shape[0]:
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 623, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2560, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 91, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 811, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 817, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 523, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 546, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset1])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 94, in fit
    self.runtime.fit(**arguments)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 195, in fit
    primitive_arguments
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 284, in _primitive_step_fit
    produce_result = model.produce(**produce_params)
  File "/user_opt/dsbox/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/data_profile.py", line 160, in produce
    inputs = dtype_detector.detector(inputs)
  File "/user_opt/dsbox/src/dsbox-datacleaning/dsbox/datapreprocessing/cleaner/dependencies/dtype_detector.py", line 57, in detector
    _logger.error(traceback.print_exc(e))
  File "/usr/lib/python3.6/traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.6/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/usr/lib/python3.6/traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "/usr/lib/python3.6/traceback.py", line 332, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'KeyError' and 'int'
[INFO] push@Candidate: (80082241797670562,None)
```

**Comment by kyao** [comment]
Also, see /dsbox_efs/runs/seed-2018-07-26-02:04/uu3_world_development_indicators/supporting_files/logs/out.txt

**Comment by RqS** [comment]
Fixed in latest dsbox-cleaning
