### ISSUE TITLE
featurizer/timeseries/timeseries_feature.py bug

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#118]
/dsbox_efs/runs/seed-2018-07-26-02:04/66_chlorineConcentration/
```
Namespace(configuration_file='/dsbox_efs/config/seed-41/partition-16/66_chlorineConcentration/search_config.json', cpus=10, debug=False, output_prefix=None, timeout=55)
Using configuation:
{'cpus': 10,
 'dataset_schema': '/dsbox_efs/dataset/seed_datasets_current/66_chlorineConcentration/66_chlorineConcentration_dataset/datasetDoc.json',
 'executables_root': '/dsbox_efs/runs/seed/66_chlorineConcentration/executables',
 'pipeline_logs_root': '/dsbox_efs/runs/seed/66_chlorineConcentration/pipelines',
 'problem_root': '/dsbox_efs/dataset/seed_datasets_current/66_chlorineConcentration/66_chlorineConcentration_problem',
 'problem_schema': '/dsbox_efs/dataset/seed_datasets_current/66_chlorineConcentration/66_chlorineConcentration_problem/problemDoc.json',
 'temp_storage_root': '/dsbox_efs/runs/seed/66_chlorineConcentration/supporting_files',
 'timeout': 55,
 'training_data_root': '/dsbox_efs/dataset/seed_datasets_current/66_chlorineConcentration/66_chlorineConcentration_dataset',
 'user_problems_root': '/dsbox_efs/runs/seed/66_chlorineConcentration/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] - dsbox.controller.controller - Top level output directory: /dsbox_efs/runs/seed/66_chlorineConcentration
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' Default_timeseries_collection_template ' has been added to template base.
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 0:SRI_Mean_Baseline_Template Selected. UCT:[None, None]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float\
64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.sri.baseline.MeanBaseline', -4476432135772146244)
[INFO] Testing finish.!!!
[INFO] Now in normal mode, will add extra train with train_dataset1
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', -4476432135772146244)
[INFO] Now are training the pipeline with all dataset and saving the pipeline.
[INFO] Hit@cache: ('d3m.primitives.sri.baseline.MeanBaseline', -4476432135772146244)
[INFO] push@Candidate: (-978493645134826292,5811b659-07da-4652-b718-4cebdfe8b5bc)
[INFO] - dsbox.controller.controller - ******************
[INFO] Writing results
{'cross_validation_metrics': [],
 'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f65a9f771d0>,
 'test_metrics': [{'metric': 'f1Macro', 'value': 0.23270440251572325}],
 'total_runtime': 215.58760714530945,
 'training_metrics': [{'metric': 'f1Macro', 'value': 0.23249299719887953}]}
[INFO] - dsbox.controller.controller - {'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f65a9f771d0>, 'training_metrics': [{'metric': 'f1Macro', 'value': 0.23249299719887953}], 'c\
ross_validation_metrics': [], 'test_metrics': [{'metric': 'f1Macro', 'value': 0.23270440251572325}], 'total_runtime': 215.58760714530945} 0.23270440251572325
[INFO] - dsbox.controller.controller - Training f1Macro = 0.23249299719887953
[INFO] - dsbox.controller.controller - Validation f1Macro = 0.23270440251572325
[INFO] - dsbox.controller.controller - ******************
[INFO] Saving training results in /dsbox_efs/runs/seed/66_chlorineConcentration.txt
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] report: 0.23270440251572325
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] UCT updated: [35.313668723678575, 122.97817793738115]
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] cache size: 1, candidates: 1
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 1:Default_timeseries_collection_template Selected. UCT:[35.313668723678575, 122.97817793738115]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.dsbox.Denormalize', -4476432135772146244)
[INFO] Push@cache: ('d3m.primitives.datasets.DatasetToDataFrame', -4476432135772146244)
[INFO] Push@cache: ('d3m.primitives.dsbox.TimeseriesToList', 28360019876937530)
[INFO] Push@cache: ('d3m.primitives.dsbox.RandomProjectionTimeSeriesFeaturization', 5122854077300089521)
n_components is 1855
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 523, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 579, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 94, in fit
    self.runtime.fit(**arguments)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 195, in fit
    primitive_arguments
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 281, in _primitive_step_fit
    model.fit()
  File "/src/dsbox-featurizer/dsbox/datapreprocessing/featurizer/timeseries/timeseries_feature.py", line 158, in fit
    self._model.fit(self._training_data)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/random_projection.py", line 366, in fit
    n_features))
ValueError: eps=0.200000 and n_samples=3100 lead to a target dimension of 1855 which is larger than the original space with n_features=166
[INFO] push@Candidate: (3854348166191296201,None)
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 378, in setup_initial_candidate
    candidate.data.update(result)
TypeError: 'NoneType' object is not iterable
[ERROR] Initial Pipeline failed, Trying a random pipeline ...
```

**Comment by ckxz105** [comment]
You need to pull the version of dsbox-featurizer after this commit, it should solve the problem https://github.com/usc-isi-i2/dsbox-featurizer/commit/14d6a253e4f2611b14c94dd7f1b95f72d46d1843
