### ISSUE TITLE
Multitable featurizer problem

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#127]
For some datasets, foreign key is indicated by 'column_index', not 'column_name'

See /dsbox_efs/runs/seed-2018-07-26-02:04/uu2_gp_hyperparameter_estimation/supporting_files/logs/out.txt

```
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] report: -inf
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] UCT updated: [16.21413539271983, 60.07383045417889, 49.50820764525503, 156.49570458608625]
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] cache size: 7, candidates: 4
[INFO] - dsbox.controller.controller - ^[[30m^[[42m[INFO] Template 3:UU3_Test_Template Selected. UCT:[16.21413539271983, 60.07383045417889, 49.50820764525503, 156.49570458608625]
[INFO] Worker started, id: <_MainProcess(MainProcess, started)> , True
[INFO] Will use normal train-test mode ( n = 1 ) to choose best primitives.
[INFO] Push@cache: ('d3m.primitives.dsbox.MultiTableFeaturization', -6233746033504171510)
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 523, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 579, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 94, in fit
    self.runtime.fit(**arguments)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 195, in fit
    primitive_arguments
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 284, in _primitive_step_fit
    produce_result = model.produce(**produce_params)
  File "/src/dsbox-featurizer/dsbox/datapreprocessing/featurizer/multiTable/multi_table_featurizer.py", line 67, in produce
    big_table = self._core(inputs)
  File "/src/dsbox-featurizer/dsbox/datapreprocessing/featurizer/multiTable/multi_table_featurizer.py", line 113, in _core
    target_column_name = column_metadata['foreign_key']['resource_id'] + "_" + column_metadata['foreign_key']['column_name']
  File "/usr/local/lib/python3.6/dist-packages/frozendict/__init__.py", line 29, in __getitem__
    return self._dict[key]
KeyError: 'column_name'
[INFO] push@Candidate: (-1346521914341251977,None)
```

**Comment by kyao** [comment]
Fix in dsbox-featurizer repo: https://github.com/usc-isi-i2/dsbox-featurizer/commit/516678427a7473c730c79a401184bfaecfe959f3
