### ISSUE TITLE
CastToType Issue 2

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#139]
CastToType with the hyperameter 'float' will raise exception if there are no float columns.

```
Traceback (most recent call last):
  File "/nfs1/dsbox-repo/kyao/dsbox-710/dsbox-ta2/python/dsbox/template/search.py", line 523, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/nfs1/dsbox-repo/kyao/dsbox-710/dsbox-ta2/python/dsbox/template/search.py", line 579, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/nfs1/dsbox-repo/kyao/dsbox-710/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 94, in fit
    self.runtime.fit(**arguments)
  File "/nfs1/dsbox-repo/kyao/dsbox-710/dsbox-ta2/python/dsbox/template/runtime.py", line 195, in fit
    primitive_arguments
  File "/nfs1/dsbox-repo/kyao/dsbox-710/dsbox-ta2/python/dsbox/template/runtime.py", line 284, in _primitive_step_fit
    produce_result = model.produce(**produce_params)
  File "/nfs1/dsbox-repo/kyao/dsbox-710/common-primitives/common_primitives/cast_to_type.py", line 78, in produce
    columns_to_use = self._get_columns(inputs.metadata, type_to_cast, self.hyperparams)
  File "/nfs1/dsbox-repo/kyao/dsbox-710/common-primitives/common_primitives/cast_to_type.py", line 114, in _get_columns
    raise ValueError("No columns to be cast to type '{type}'.".format(type=type_to_cast))
ValueError: No columns to be cast to type '<class 'float'>'.
```

**Comment by liangmuxin** [comment]
added donothing with casttotype in template
