### ISSUE TITLE
classification_with_feature_selection template sometimes fails on LL0_1493_one_hundred_plants_texture

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#174]
```
[INFO] Hit@cache: ('d3m.primitives.data.CastToType', -7619052573523678693)
[INFO] Hit@cache: ('d3m.primitives.dsbox.MeanImputation', 8541664555706428423)
[INFO] Hit@cache: ('d3m.primitives.dsbox.Encoder', -6198703753328499714)
2018-08-08 14:38:17,919 [INFO] dsbox.template.runtime -- Primitive Fit. 'id': 'eb5fe752-f22a-4090-948b-aafcef203bf5', '(name, hash)': ('d3m.primitives.data.CastToType', '-7619052573523678693'), 'worker_id': '<ForkProcess(ForkPoolWorker-38, started daemon)>'.
[INFO] Hit@cache: ('d3m.primitives.data.CastToType', -7619052573523678693)
[INFO] Hit@cache: ('d3m.primitives.data.CastToType', -7619052573523678693)
[INFO] Hit@cache: ('d3m.primitives.dsbox.MeanImputation', 8541664555706428423)
2018-08-08 14:38:17,987 [INFO] dsbox.template.runtime -- Primitive Fit. 'id': 'eb5fe752-f22a-4090-948b-aafcef203bf5', '(name, hash)': ('d3m.primitives.data.CastToType', '-7619052573523678693'), 'worker_id': '<ForkProcess(ForkPoolWorker-40, started daemon)>'.
2018-08-08 14:38:17,990 [INFO] dsbox.template.runtime -- Primitive Fit. 'id': '7894b699-61e9-3a50-ac9f-9bc510466667', '(name, hash)': ('d3m.primitives.dsbox.MeanImputation', '8541664555706428423'), 'worker_id': '<ForkProcess(ForkPoolWorker-37, started daemon)>'.
2018-08-08 14:38:17,990 [INFO] dsbox.template.runtime -- Primitive Fit. 'id': '1055a114-5c94-33b0-9100-675fd0200e72', '(name, hash)': ('d3m.primitives.sklearn_wrap.SKGenericUnivariateSelect', '-6922488208708182333'), 'worker_id': '<ForkProcess(ForkPoolWorker-32, started daemon)>'.
[INFO] Push@cache: ('d3m.primitives.sklearn_wrap.SKGenericUnivariateSelect', -6922488208708182333)
[INFO] Hit@cache: ('d3m.primitives.data.CastToType', -7619052573523678693)
2018-08-08 14:38:18,018 [ERROR] dsbox.template.search -- Evaulate pipeline failed
Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 564, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 621, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 99, in fit
    self.runtime.fit(**arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 213, in fit
    primitive_arguments
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 307, in _primitive_step_fit
    model.fit()
  File "/nfs1/dsbox-repo/stan/sklearn-wrap/sklearn_wrap/SKGenericUnivariateSelect.py", line 148, in fit
    self._clf.fit(self._training_inputs, sk_training_output)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py", line 349, in fit
    score_func_ret = self.score_func(X, y)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py", line 285, in f_regression
    y = y - np.mean(y)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2957, in mean
    out=out, **kwargs)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/numpy/core/_methods.py", line 82, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'str' and 'int'
Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 564, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 621, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 99, in fit
    self.runtime.fit(**arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 213, in fit
    primitive_arguments
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 307, in _primitive_step_fit
    model.fit()
  File "/nfs1/dsbox-repo/stan/sklearn-wrap/sklearn_wrap/SKGenericUnivariateSelect.py", line 148, in fit
    self._clf.fit(self._training_inputs, sk_training_output)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py", line 349, in fit
    score_func_ret = self.score_func(X, y)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py", line 285, in f_regression
    y = y - np.mean(y)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2957, in mean
    out=out, **kwargs)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-710/lib/python3.6/site-packages/numpy/core/_methods.py", line 82, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by liangmuxin** [comment]
Does "sometime" mean for one of the pipelines or the whole template?

**Comment by serbanstan** [comment]
The template mostly works, pipelines only fail occasionally. It would be good to know why though.

**Comment by liangmuxin** [comment]
Get it, then we can test on this single choice

**Comment by liangmuxin** [comment]
univariate_selection has two method, one for regression and one for classification, that's why previously we have selector_reg() and selector_cls(), but now we only have that for regression. I will fix it and push
