### ISSUE TITLE
LL1_23513_kdd98: Dropped target column?

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#189]
LL1_23513_kdd98 is a large column dataset. It appears we dropped the target column during load.

```
[INFO] Push@cache: ('d3m.primitives.data.ExtractColumnsBySemanticTypes', -935882892361098643)
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 564, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration, cache, dump2disk)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/search.py", line 623, in _evaluate
    fitted_pipeline.fit(cache=cache, inputs=[self.train_dataset2[each_repeat]])
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 101, in fit
    self.runtime.fit(**arguments)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 218, in fit
    primitive_arguments
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 341, in _primitive_step_fit
    produce_result = model.produce(**produce_params).value
  File "/user_opt/dsbox/src/common-primitives/common_primitives/extract_columns_semantic_types.py", line 77, in produce
    columns = self._get_columns(inputs.metadata, self.hyperparams)
  File "/user_opt/dsbox/src/common-primitives/common_primitives/extract_columns_semantic_types.py", line 92, in _get_columns
    semantic_types=hyperparams['semantic_types'],
ValueError: Input data has no columns matching semantic types: ('https://metadata.datadrivendiscovery.org/types/Target', 'https://metadata.datadrivendiscovery.org/types/SuggestedTarget')

```

**Comment by liangmuxin** [comment]
Target was retrieved but there are still problems
