### ISSUE TITLE
On branch template-phaseI-refactored

### ISSUE THREAD

**Issue by liangmuxin** [usc-isi-i2/dsbox-ta2#202]
`(d3m-devel-710) MuxindeMacBook-Pro:python muxin$ python ta2-search /Users/muxin/Desktop/ISI/dsbox-env/configs/seed/38_sick/search_config.json 
Namespace(configuration_file='/Users/muxin/Desktop/ISI/dsbox-env/configs/seed/38_sick/search_config.json', cpus=-1, debug=False, output_prefix=None, timeout=-1)
[INFO] Time out is  -3
Using configuation:
{'dataset_schema': '/Users/muxin/Desktop/ISI/dsbox-env/data/datasets/seed_datasets_current/38_sick/38_sick_dataset/datasetDoc.json',
 'executables_root': '/Users/muxin/Desktop/ISI/dsbox-env/output/seed/38_sick/executables',
 'pipeline_logs_root': '/Users/muxin/Desktop/ISI/dsbox-env/output/seed/38_sick/pipelines',
 'problem_root': '/Users/muxin/Desktop/ISI/dsbox-env/data/datasets/seed_datasets_current/38_sick/38_sick_problem',
 'problem_schema': '/Users/muxin/Desktop/ISI/dsbox-env/data/datasets/seed_datasets_current/38_sick/38_sick_problem/problemDoc.json',
 'temp_storage_root': '/Users/muxin/Desktop/ISI/dsbox-env/output/seed/38_sick/supporting_files',
 'training_data_root': '/Users/muxin/Desktop/ISI/dsbox-env/data/datasets/seed_datasets_current/38_sick/38_sick_dataset',
 'user_problems_root': '/Users/muxin/Desktop/ISI/dsbox-env/output/seed/38_sick/user_problems'}
[INFO] No test data config found! Will split the data.
[INFO] Template choices:
Template ' SRI_Mean_Baseline_Template ' has been added to template base.
Template ' default_classification_template ' has been added to template base.
Template ' naive_bayes_classification_template ' has been added to template base.
Template ' classification_with_feature_selection ' has been added to template base.
Template ' dsbox_classification_template ' has been added to template base.
[Info] Not splitting dataset. Stratified shuffle failed
timer started: 59 min
Traceback (most recent call last):
  File "ta2-search", line 207, in <module>
    result = main(args)
  File "ta2-search", line 131, in main
    status = controller.train()
  File "/Users/muxin/Desktop/ISI/dsbox-env/dsbox-ta2/python/dsbox/controller/controller.py", line 898, in train
    self._run_RandomDimSearch()
  File "/Users/muxin/Desktop/ISI/dsbox-env/dsbox-ta2/python/dsbox/controller/controller.py", line 435, in _run_RandomDimSearch
    report = searchMethod.search(num_iter=2)
  File "/Users/muxin/Desktop/ISI/dsbox-env/dsbox-ta2/python/dsbox/combinatorial_search/RandomDimensionalSearch.py", line 239, in search
    self.job_manager.start_workers(target=self._evaluate_template)
  File "/Users/muxin/Desktop/ISI/dsbox-env/dsbox-ta2/python/dsbox/JobManager/DistributedJobManager.py", line 35, in start_workers
    self.job_pool = Pool(processes=self.proc_num)
  File "/Users/muxin/miniconda3/envs/d3m-devel-710/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/Users/muxin/miniconda3/envs/d3m-devel-710/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1`

And it stuck here

**Comment by liangmuxin** [comment]
Should add number of processes as parameter
