### ISSUE TITLE
Cache error

### ISSUE THREAD

**Issue by RqS** [usc-isi-i2/dsbox-ta2#210]
```
Process Process-1:
Traceback (most recent call last):
  File "/anaconda3/envs/d3m-devel-710/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/envs/d3m-devel-710/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/JobManager/mplog.py", line 52, in logged_call
    func(*args, **kwargs)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/controller/controller.py", line 439, in _run_RandomDimSearch
    report = searchMethod.search(num_iter=2)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/combinatorial_search/RandomDimensionalSearch.py", line 243, in search
    self._search_templates(num_iter=num_iter)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/combinatorial_search/RandomDimensionalSearch.py", line 259, in _search_templates
    self.search_one_iter(search=search, max_per_dim=5)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/combinatorial_search/RandomDimensionalSearch.py", line 113, in search_one_iter
    self._get_evaluation_results(template_name=search.template.template['name'])
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/combinatorial_search/TemplateSpaceParallelBaseSearch.py", line 111, in _get_evaluation_results
    self._add_report_to_candidate_cache(kwargs, report, template_name)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/combinatorial_search/TemplateSpaceParallelBaseSearch.py", line 123, in _add_report_to_candidate_cache
    self.cacheManager.candidate_cache.push(report)
  File "/Users/runqishao/Documents/github/dsbox-rqs/dsbox-ta2/python/dsbox/JobManager/cache.py", line 95, in push
    assert match[k] is None or match[k]['value'] is None or\
TypeError: list indices must be integers or slices, not str
```
[
[out.txt](https://github.com/usc-isi-i2/dsbox-ta2/files/2389968/out.txt)
](url)

**Comment by proska** [comment]
Is this still an issue? Please update me if you still have the same problem
