### ISSUE TITLE
Should not assume datasetDoc 'redacted' field exists

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#237]
See LL1_crime_chicago

```
02-18 07:13:30 [INFO] dsbox.controller.controller -- Top level output directory: /output
02-18 07:13:30 [ERROR] grpc._server -- Exception iterating responses: 'redacted'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_server.py", line 409, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/server/ta2_servicer.py", line 257, in GetSearchSolutionsResults
    self.controller.initialize_from_ta3(problem_config)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 794, in initialize_from_ta3
    self.all_dataset = loader.load(dataset_uri='file://{}'.format(json_file))
  File "/usr/local/lib/python3.6/dist-packages/d3m/container/dataset.py", line 504, in load
    'redacted': dataset_doc['about']['redacted'],
KeyError: 'redacted'
```

**Comment by kyao** [comment]
Already fixed by https://gitlab.com/datadrivendiscovery/d3m/commit/5371cd20545c4bb4e68cb2f7f197ddf8a2f71776
