### ISSUE TITLE
controller.generate_dataset_splits() error

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#255]
Here is the output using the 1567_poker_hand dataset: 
> 2019-05-13 18:31:17 [INFO] dsbox.datapreprocessing.cleaner.splitter -- The row number of the input dataset is very large, will split part of them.
2019-05-13 18:31:17 [INFO] dsbox.datapreprocessing.cleaner.splitter -- The input dataset's main resource shape is: (820008, 12)
2019-05-13 18:31:17 [INFO] dsbox.datapreprocessing.cleaner.splitter -- sampling needed.
2019-05-13 18:31:17 [INFO] dsbox.datapreprocessing.cleaner.splitter -- Now sampling rows.
2019-05-13 18:31:17 [WARNING] d3m.deprecate -- dsbox.datapreprocessing.cleaner.splitter: Calling a deprecated function 'cut_dataset' in '/src/dsbox-primitives/dsbox/datapreprocessing/cleaner/splitter.py' at line 259: use Dataset.select_rows method instead
2019-05-13 18:31:17 [INFO] dsbox.datapreprocessing.cleaner.splitter -- Sampling rows finished.
2019-05-13 18:31:17 [INFO] dsbox.datapreprocessing.cleaner.splitter -- The sampled dataset's main resource shape is: (100000, 12)
2019-05-13 18:31:17 [ERROR] grpc._server -- Exception iterating responses: Can only compare identically-labeled DataFrame objects
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_server.py", line 423, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/server/ta2_servicer.py", line 263, in GetSearchSolutionsResults
    _ = self.controller.train()
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 1474, in train
    self.generate_dataset_splits()
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/controller/controller.py", line 1534, in generate_dataset_splits
    if self.all_dataset != train_split.value:
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/ops.py", line 1613, in f
    raise ValueError('Can only compare identically-labeled '
ValueError: Can only compare identically-labeled DataFrame objects

**Comment by ckxz105** [comment]
fixed
