### ISSUE TITLE
ta2-search is no longer working

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#27]
```
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Namespace(configuration_file='/nas/home/stan/dsbox/runs2/config-seed/38_sick_config.json', cpus=-1, debug=False, output_prefix=None, timeout=-1)

Using configuation:
{'cpus': '10',
 'dataset_schema': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/38_sick/38_sick_dataset/datasetDoc.json',
 'executables_root': '/nas/home/stan/dsbox/runs2/output-seed/38_sick/executables',
 'pipeline_logs_root': '/nas/home/stan/dsbox/runs2/output-seed/38_sick/logs',
 'problem_root': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/38_sick/38_sick_problem',
 'problem_schema': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/38_sick/38_sick_problem/problemDoc.json',
 'ram': '10Gi',
 'temp_storage_root': '/nas/home/stan/dsbox/runs2/output-seed/38_sick/temp',
 'timeout': 9,
 'training_data_root': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/38_sick/38_sick_dataset'}
{'structural_type': <class 'pandas.core.frame.DataFrame'>, 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table', 'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'), 'dimension': {'name': 'rows', 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/TabularRow',), 'length': 3017}}
{'dimension': <FrozenOrderedDict OrderedDict([('name', 'rows'), ('semantic_types', ('https://metadata.datadrivendiscovery.org/types/TabularRow',)), ('length', 3017)])>,
 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table',
                    'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'),
 'structural_type': <class 'pandas.core.frame.DataFrame'>}
{'structural_type': <class 'pandas.core.frame.DataFrame'>, 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table', 'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'), 'dimension': {'name': 'rows', 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/TabularRow',), 'length': 755}}
{'dimension': <FrozenOrderedDict OrderedDict([('name', 'rows'), ('semantic_types', ('https://metadata.datadrivendiscovery.org/types/TabularRow',)), ('length', 755)])>,
 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table',
                    'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'),
 'structural_type': <class 'pandas.core.frame.DataFrame'>}
{'name': 'impute_step', 'primitives': [{'primitive': 'd3m.primitives.sklearn_wrap.SKImputer', 'hyperparameters': {'strategy': ['mean', 'median', 'most_frequent']}}], 'inputs': ['cast_1_step']} is dict
***************
Pipeline failed {'model_step': {'primitive': 'd3m.primitives.sklearn_wrap.SKGradientBoostingClassifier', 'hyperparameters': {'n_estimators': [87, 55]}}}
{'name': 'impute_step', 'primitives': [{'primitive': 'd3m.primitives.sklearn_wrap.SKImputer', 'hyperparameters': {'strategy': ['mean', 'median', 'most_frequent']}}], 'inputs': ['cast_1_step']} is dict
Pipeline failed {'model_step': {'primitive': 'd3m.primitives.sklearn_wrap.SKGradientBoostingClassifier', 'hyperparameters': {'n_estimators': [87, 55]}}}
{'name': 'impute_step', 'primitives': [{'primitive': 'd3m.primitives.sklearn_wrap.SKImputer', 'hyperparameters': {'strategy': ['mean', 'median', 'most_frequent']}}], 'inputs': ['cast_1_step']} is dict
Error in sys.excepthook:
Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/miniconda/envs/d3m-devel/lib/python3.6/site-packages/theano/gof/link.py", line 79, in thunk_hook
    __excepthook(type, value, trace)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/d3m-devel/lib/python3.6/site-packages/pytypes/util.py", line 820, in _pytypes_excepthook
    traceback.print_exception(exctype, value, tb, _calc_traceback_limit(tb))
  File "/nfs1/dsbox-repo/stan/miniconda/envs/d3m-devel/lib/python3.6/site-packages/pytypes/util.py", line 764, in _calc_traceback_limit
    if tb2.tb_next.tb_frame.f_code.co_filename.split(os.sep)[-2] == 'pytypes' and not \
IndexError: list index out of range

Original exception was:
Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 187, in setup_initial_candidate
    result = self.evaluate(candidate)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 278, in evaluate_pipeline
    value, new_data = self._evaluate(configuration)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 289, in _evaluate
    run.fit(inputs=[self.train_dataset])
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 119, in fit
    primitives_outputs[n_step] = self._primitive_step_fit(n_step, self.pipeline_description.steps[n_step], primitive_arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 162, in _primitive_step_fit
    primitive_hyperparams.defaults(), **custom_hyperparams))
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 2182, in __init__
    self.validate(values)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 2244, in validate
    cls.configuration[name].validate(value)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 933, in validate
    super().validate(value)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 194, in validate
    value=value, for_name=self._for_name(), structural_type=self.structural_type,
d3m.exceptions.InvalidArgumentTypeError: Value '[87, 55]' for hyper-parameter 'n_estimators' is not an instance of the structural type: <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 194, in setup_initial_candidate
    result = self.evaluate(candidate)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 278, in evaluate_pipeline
    value, new_data = self._evaluate(configuration)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 289, in _evaluate
    run.fit(inputs=[self.train_dataset])
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 119, in fit
    primitives_outputs[n_step] = self._primitive_step_fit(n_step, self.pipeline_description.steps[n_step], primitive_arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 162, in _primitive_step_fit
    primitive_hyperparams.defaults(), **custom_hyperparams))
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 2182, in __init__
    self.validate(values)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 2244, in validate
    cls.configuration[name].validate(value)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 933, in validate
    super().validate(value)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 194, in validate
    value=value, for_name=self._for_name(), structural_type=self.structural_type,
d3m.exceptions.InvalidArgumentTypeError: Value '[87, 55]' for hyper-parameter 'n_estimators' is not an instance of the structural type: <class 'int'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ta2-search", line 155, in <module>
    result = main(args)
  File "ta2-search", line 128, in main
    status = controller.train()
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/controller/controller.py", line 268, in train
    candidate, value = search.search_one_iter()
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 101, in search_one_iter
    candidate, candidate_value = self.setup_initial_candidate(candidate_in)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 199, in setup_initial_candidate
    result = self.evaluate(candidate)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 278, in evaluate_pipeline
    value, new_data = self._evaluate(configuration)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 289, in _evaluate
    run.fit(inputs=[self.train_dataset])
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 119, in fit
    primitives_outputs[n_step] = self._primitive_step_fit(n_step, self.pipeline_description.steps[n_step], primitive_arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 162, in _primitive_step_fit
    primitive_hyperparams.defaults(), **custom_hyperparams))
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 2182, in __init__
    self.validate(values)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 2244, in validate
    cls.configuration[name].validate(value)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 933, in validate
    super().validate(value)
  File "/nfs1/dsbox-repo/stan/d3m/d3m/metadata/hyperparams.py", line 194, in validate
    value=value, for_name=self._for_name(), structural_type=self.structural_type,
d3m.exceptions.InvalidArgumentTypeError: Value '[87, 55]' for hyper-parameter 'n_estimators' is not an instance of the structural type: <class 'int'>
```

**Comment by serbanstan** [comment]
Added a try/catch statement in runtime.py to run primitives with default hyperparameters, in case our custom hyperparameters don't work.
