### ISSUE TITLE
System fails if one subprocess fails

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#49]
Running a template with several classifiers crashes the system if one classifier crashes. In a bit more detail - if one classifier fails, we don't get any results back, even if some other classifier might have succeeded.

Template 1:
```
class DefaultClassificationTemplate(DSBoxTemplate):
    def __init__(self):
        DSBoxTemplate.__init__(self)
        self.template = {
            "name": "Default_classification_template",
            "taskSubtype" : {TaskSubtype.BINARY.name,TaskSubtype.MULTICLASS.name},
            "taskType": TaskType.CLASSIFICATION.name,  # See TaskType, range include 'CLASSIFICATION', 'CLUSTERING', 'COLLABORATIVE_FILTERING', 'COMMUNITY_DETECTION', 'GRAPH_CLUSTERING', 'GRAPH_MATCHING', 'LINK_PREDICTION', 'REGRESSION', 'TIME_SERIES_FORECASTING', 'VERTEX_NOMINATION'
            "inputType": "table",  # See SEMANTIC_TYPES.keys() for range of values
            "output": "model_step",  # Name of the final step generating the prediction
            "target": "extract_target_step",  # Name of the step generating the ground truth
            "steps": [
                {
                    "name": "denormalize_step",
                    "primitives": ["d3m.primitives.datasets.Denormalize"],
                    "inputs": ["template_input"]
                },
                {
                    "name": "to_dataframe_step",
                    "primitives": ["d3m.primitives.datasets.DatasetToDataFrame"],
                    "inputs": ["denormalize_step"]
                },
                {
                    "name": "extract_attribute_step",
                    "primitives": [{
                        "primitive": "d3m.primitives.data.ExtractColumnsBySemanticTypes",
                        "hyperparameters":
                            {
                                'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Attribute',),
                                'use_columns': (),
                                'exclude_columns': ()
                            }
                    }],
                    "inputs": ["to_dataframe_step"]
                },
                {
                    "name": "column_parser_step",
                    "primitives": ["d3m.primitives.data.ColumnParser"],
                    "inputs": ["extract_attribute_step"]
                },
                {
                    "name": "cast_1_step",
                    "primitives": ["d3m.primitives.data.CastToType"],
                    "inputs": ["column_parser_step"]
                },
                {
                    "name": "impute_step",
                    "primitives": ["d3m.primitives.sklearn_wrap.SKImputer"],
                    "inputs": ["cast_1_step"]
                },
                {
                    "name": "extract_target_step",
                    "primitives": [{
                        "primitive": "d3m.primitives.data.ExtractColumnsBySemanticTypes",
                        "hyperparameters":
                            {'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Target', 'https://metadata.datadrivendiscovery.org/types/SuggestedTarget',),
                             'use_columns': (),
                             'exclude_columns': ()
                             }
                    }],
                    "inputs": ["to_dataframe_step"]
                },
                {
                    "name": "model_step",
                    "primitives": [{
                        # "primitive":
                        #     "d3m.primitives.sklearn_wrap.SKBernoulliNB",
                        # "hyperparameters": { },
                        # },
                        # {"primitive":
                        #     "d3m.primitives.sklearn_wrap.SKGaussianNB",
                        # "hyperparameters": { },
                        # },
                        # {"primitive":
                        #     "d3m.primitives.sklearn_wrap.SKGradientBoostingClassifier",
                        # "hyperparameters": { }
                        # },
                        # {"primitive":
                        #     "d3m.primitives.sklearn_wrap.SKMultinomialNB",
                        # "hyperparameters": { }
                        # },
                        # {"primitive":
                        #     "d3m.primitives.sklearn_wrap.SKPassiveAggressiveClassifier",
                        # "hyperparameters": { }
                        # },
                        # {"primitive":
                        #     "d3m.primitives.sklearn_wrap.SKQuadraticDiscriminantAnalysis",
                        # "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKRandomForestClassifier",
                        "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKSVC",
                        "hyperparameters": { }
                        }],
                    "inputs": ["impute_step", "extract_target_step"]
                }
            ]
        }
    # @override
    def importance(datset, problem_description):
        return 7
```

Result 1:

```
(dsbox-devel-418) [stan@dsbox01 python]$ python ta2-search /nas/home/stan/dsbox/runs2/config-seed/4550_MiceProtein_config.json 
Namespace(configuration_file='/nas/home/stan/dsbox/runs2/config-seed/4550_MiceProtein_config.json', cpus=-1, debug=False, output_prefix=None, timeout=-1)
Using configuation:
{'cpus': '10',
 'dataset_schema': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_dataset/datasetDoc.json',
 'executables_root': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein/executables',
 'pipeline_logs_root': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein/logs',
 'problem_root': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_problem',
 'problem_schema': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_problem/problemDoc.json',
 'ram': '10Gi',
 'saved_pipeline_ID': '',
 'saving_folder_loc': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein',
 'temp_storage_root': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein/temp',
 'timeout': 9,
 'training_data_root': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_dataset'}
[INFO] No test data config found! Will split the data.
[INFO] Succesfully parsed test data
{'structural_type': <class 'd3m.container.pandas.DataFrame'>, 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table', 'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'), 'dimension': {'name': 'rows', 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/TabularRow',), 'length': 865}}
{'dimension': <FrozenOrderedDict OrderedDict([('name', 'rows'), ('semantic_types', ('https://metadata.datadrivendiscovery.org/types/TabularRow',)), ('length', 865)])>,
 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table',
                    'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'),
 'structural_type': <class 'd3m.container.pandas.DataFrame'>}
{'structural_type': <class 'd3m.container.pandas.DataFrame'>, 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table', 'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'), 'dimension': {'name': 'rows', 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/TabularRow',), 'length': 215}}
{'dimension': <FrozenOrderedDict OrderedDict([('name', 'rows'), ('semantic_types', ('https://metadata.datadrivendiscovery.org/types/TabularRow',)), ('length', 215)])>,
 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table',
                    'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'),
 'structural_type': <class 'd3m.container.pandas.DataFrame'>}
[INFO] Template choices:
Template ' Default_classification_template ' has been added to template base.
Error: Wrong format of the configuration space data: No primitive name found!
[INFO] Worker started, id: <_MainProcess(MainProcess, started)>
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-07-06 17:34:53.092736: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
****************************************************************************************************
[INFO] Running Pool: 1
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-1, started daemon)>
[INFO] Best index: 0
[0.06633946682121125]
******************
[INFO] Writing results
{'fitted_pipeline': <dsbox.pipeline.fitted_pipeline.FittedPipeline object at 0x7f06468dd978>, 'training_metrics': [{'metric': 'f1Macro', 'value': 0.892201914107038}], 'validation_metrics': [{'metric': 'f1Macro', 'value': 0.06633946682121125}]}
{'denormalize_step': {'primitive': 'd3m.primitives.datasets.Denormalize', 'hyperparameters': {}}, 'to_dataframe_step': {'primitive': 'd3m.primitives.datasets.DatasetToDataFrame', 'hyperparameters': {}}, 'extract_attribute_step': {'primitive': 'd3m.primitives.data.ExtractColumnsBySemanticTypes', 'hyperparameters': {'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Attribute',)}}, 'column_parser_step': {'primitive': 'd3m.primitives.data.ColumnParser', 'hyperparameters': {}}, 'cast_1_step': {'primitive': 'd3m.primitives.data.CastToType', 'hyperparameters': {}}, 'impute_step': {'primitive': 'd3m.primitives.sklearn_wrap.SKImputer', 'hyperparameters': {}}, 'extract_target_step': {'primitive': 'd3m.primitives.data.ExtractColumnsBySemanticTypes', 'hyperparameters': {'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Target', 'https://metadata.datadrivendiscovery.org/types/SuggestedTarget')}}, 'model_step': {'primitive': 'd3m.primitives.sklearn_wrap.SKSVC', 'hyperparameters': {}}} 0.06633946682121125
Training f1Macro = 0.892201914107038
Validation f1Macro = 0.06633946682121125
******************
[INFO] Saving training results in /nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein.txt
******************
[INFO] Saving Best Pipeline
*+*+*+*+*+*+*+*+*+*+
Skipping testing, it takes a bit long
[INFO] Testing Done
[INFO] The time used for running program is 103.63000000000001 seconds.
```

Template 2:
```class DefaultClassificationTemplate(DSBoxTemplate):
    def __init__(self):
        DSBoxTemplate.__init__(self)
        self.template = {
            "name": "Default_classification_template",
            "taskSubtype" : {TaskSubtype.BINARY.name,TaskSubtype.MULTICLASS.name},
            "taskType": TaskType.CLASSIFICATION.name,  # See TaskType, range include 'CLASSIFICATION', 'CLUSTERING', 'COLLABORATIVE_FILTERING', 'COMMUNITY_DETECTION', 'GRAPH_CLUSTERING', 'GRAPH_MATCHING', 'LINK_PREDICTION', 'REGRESSION', 'TIME_SERIES_FORECASTING', 'VERTEX_NOMINATION'
            "inputType": "table",  # See SEMANTIC_TYPES.keys() for range of values
            "output": "model_step",  # Name of the final step generating the prediction
            "target": "extract_target_step",  # Name of the step generating the ground truth
            "steps": [
                {
                    "name": "denormalize_step",
                    "primitives": ["d3m.primitives.datasets.Denormalize"],
                    "inputs": ["template_input"]
                },
                {
                    "name": "to_dataframe_step",
                    "primitives": ["d3m.primitives.datasets.DatasetToDataFrame"],
                    "inputs": ["denormalize_step"]
                },
                {
                    "name": "extract_attribute_step",
                    "primitives": [{
                        "primitive": "d3m.primitives.data.ExtractColumnsBySemanticTypes",
                        "hyperparameters":
                            {
                                'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Attribute',),
                                'use_columns': (),
                                'exclude_columns': ()
                            }
                    }],
                    "inputs": ["to_dataframe_step"]
                },
                {
                    "name": "column_parser_step",
                    "primitives": ["d3m.primitives.data.ColumnParser"],
                    "inputs": ["extract_attribute_step"]
                },
                {
                    "name": "cast_1_step",
                    "primitives": ["d3m.primitives.data.CastToType"],
                    "inputs": ["column_parser_step"]
                },
                {
                    "name": "impute_step",
                    "primitives": ["d3m.primitives.sklearn_wrap.SKImputer"],
                    "inputs": ["cast_1_step"]
                },
                {
                    "name": "extract_target_step",
                    "primitives": [{
                        "primitive": "d3m.primitives.data.ExtractColumnsBySemanticTypes",
                        "hyperparameters":
                            {'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Target', 'https://metadata.datadrivendiscovery.org/types/SuggestedTarget',),
                             'use_columns': (),
                             'exclude_columns': ()
                             }
                    }],
                    "inputs": ["to_dataframe_step"]
                },
                {
                    "name": "model_step",
                    "primitives": [{
                        "primitive":
                            "d3m.primitives.sklearn_wrap.SKBernoulliNB",
                        "hyperparameters": { },
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKGaussianNB",
                        "hyperparameters": { },
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKGradientBoostingClassifier",
                        "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKMultinomialNB",
                        "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKPassiveAggressiveClassifier",
                        "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKQuadraticDiscriminantAnalysis",
                        "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKRandomForestClassifier",
                        "hyperparameters": { }
                        },
                        {"primitive":
                            "d3m.primitives.sklearn_wrap.SKSVC",
                        "hyperparameters": { }
                        }],
                    "inputs": ["impute_step", "extract_target_step"]
                }
            ]
        }
    # @override
    def importance(datset, problem_description):
        return 7
```

Result 2:
```(dsbox-devel-418) [stan@dsbox01 python]$ python ta2-search /nas/home/stan/dsbox/runs2/config-seed/4550_MiceProtein_config.json 
Namespace(configuration_file='/nas/home/stan/dsbox/runs2/config-seed/4550_MiceProtein_config.json', cpus=-1, debug=False, output_prefix=None, timeout=-1)
Using configuation:
{'cpus': '10',
 'dataset_schema': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_dataset/datasetDoc.json',
 'executables_root': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein/executables',
 'pipeline_logs_root': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein/logs',
 'problem_root': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_problem',
 'problem_schema': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_problem/problemDoc.json',
 'ram': '10Gi',
 'saved_pipeline_ID': '',
 'saving_folder_loc': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein',
 'temp_storage_root': '/nfs1/dsbox-repo/stan/dsbox-ta2/python/output/4550_MiceProtein/temp',
 'timeout': 9,
 'training_data_root': '/nfs1/dsbox-repo/data/datasets/seed_datasets_current/4550_MiceProtein/4550_MiceProtein_dataset'}
[INFO] No test data config found! Will split the data.
[INFO] Succesfully parsed test data
{'structural_type': <class 'd3m.container.pandas.DataFrame'>, 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table', 'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'), 'dimension': {'name': 'rows', 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/TabularRow',), 'length': 865}}
{'dimension': <FrozenOrderedDict OrderedDict([('name', 'rows'), ('semantic_types', ('https://metadata.datadrivendiscovery.org/types/TabularRow',)), ('length', 865)])>,
 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table',
                    'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'),
 'structural_type': <class 'd3m.container.pandas.DataFrame'>}
{'structural_type': <class 'd3m.container.pandas.DataFrame'>, 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table', 'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'), 'dimension': {'name': 'rows', 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/TabularRow',), 'length': 215}}
{'dimension': <FrozenOrderedDict OrderedDict([('name', 'rows'), ('semantic_types', ('https://metadata.datadrivendiscovery.org/types/TabularRow',)), ('length', 215)])>,
 'semantic_types': ('https://metadata.datadrivendiscovery.org/types/Table',
                    'https://metadata.datadrivendiscovery.org/types/DatasetEntryPoint'),
 'structural_type': <class 'd3m.container.pandas.DataFrame'>}
[INFO] Template choices:
Template ' Default_classification_template ' has been added to template base.
[INFO] Worker started, id: <_MainProcess(MainProcess, started)>
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-07-06 17:45:17.063880: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
****************************************************************************************************
[INFO] Running Pool: 7
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-2, started daemon)>
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-3, started daemon)>
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-1, started daemon)>
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-4, started daemon)>
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-5, started daemon)>
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-6, started daemon)>
[INFO] Worker started, id: <ForkProcess(ForkPoolWorker-7, started daemon)>
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function covariances_ is deprecated; Attribute covariances_ was deprecated in version 0.19 and will be removed in 0.21. Use covariance_ instead
  warnings.warn(msg, category=DeprecationWarning)
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function covariances_ is deprecated; Attribute covariances_ was deprecated in version 0.19 and will be removed in 0.21. Use covariance_ instead
  warnings.warn(msg, category=DeprecationWarning)
/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 330, in evaluate_pipeline
    evaluation_result = self._evaluate(configuration)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 342, in _evaluate
    fitted_pipeline.fit(inputs=[self.train_dataset])
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/pipeline/fitted_pipeline.py", line 86, in fit
    self.runtime.fit(**arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 124, in fit
    primitives_outputs[n_step] = self._primitive_step_fit(n_step, primitive_step, primitive_arguments)
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/runtime.py", line 170, in _primitive_step_fit
    model.fit()
  File "/nfs1/dsbox-repo/stan/sklearn-wrap/sklearn_wrap/SKMultinomialNB.py", line 144, in fit
    self._clf.fit(self._training_inputs, sk_training_output)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/naive_bayes.py", line 604, in fit
    self._count(X, Y)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/site-packages/sklearn/naive_bayes.py", line 708, in _count
    raise ValueError("Input X must be non-negative")
ValueError: Input X must be non-negative
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs1/dsbox-repo/stan/dsbox-ta2/python/dsbox/template/search.py", line 166, in search_one_iter
    results = p.map(self.evaluate, new_candidates)
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/nfs1/dsbox-repo/stan/miniconda/envs/dsbox-devel-418/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: Input X must be non-negative
[ERROR] No Candidate worked!: []
[ERROR] not candidate!
*+*+*+*+*+*+*+*+*+*+
Skipping testing, it takes a bit long
[INFO] Testing Done
[INFO] The time used for running program is 100.75999999999999 seconds.```

**Comment by proska** [comment]
This is a multiprocessing.Pool implementation thing that kills all the processes when one throw exception. I should use a different method to reimplement it.

**Comment by proska** [comment]
Fixed in https://github.com/usc-isi-i2/dsbox-ta2/commit/86abed03886bb76d13529b7980ebece1777c9bd1
